/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface;

import business.Accountdirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author KARISHMA GAWALI
 */
public class AccountManageWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Accountdirectory accountdirectory;

    /**
     * Creates new form AccountManageWorkAreaJPanel
     */
 

    AccountManageWorkAreaJPanel(JPanel userProcessContainer, Accountdirectory accountdirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.accountdirectory = accountdirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncreateaccount = new javax.swing.JButton();
        btnmanageaccount = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 0));

        btncreateaccount.setBackground(new java.awt.Color(0, 0, 0));
        btncreateaccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncreateaccount.setForeground(new java.awt.Color(255, 255, 255));
        btncreateaccount.setText("Create Account");
        btncreateaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateaccountActionPerformed(evt);
            }
        });

        btnmanageaccount.setBackground(new java.awt.Color(0, 0, 0));
        btnmanageaccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnmanageaccount.setForeground(new java.awt.Color(255, 255, 255));
        btnmanageaccount.setText("Manage Account");
        btnmanageaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanageaccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmanageaccount)
                    .addComponent(btncreateaccount))
                .addContainerGap(413, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btncreateaccount)
                .addGap(39, 39, 39)
                .addComponent(btnmanageaccount)
                .addContainerGap(260, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncreateaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateaccountActionPerformed
        // TODO add your handling code here:
        CreateAccountJPanel panel = new CreateAccountJPanel(userProcessContainer,accountdirectory);
        userProcessContainer.add("CreateAccountJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    
    }//GEN-LAST:event_btncreateaccountActionPerformed

    private void btnmanageaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanageaccountActionPerformed
        // TODO add your handling code here:
        ManageAccountJPanel panel = new ManageAccountJPanel(userProcessContainer,accountdirectory);
        userProcessContainer.add("ManageAccountJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnmanageaccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreateaccount;
    private javax.swing.JButton btnmanageaccount;
    // End of variables declaration//GEN-END:variables
}
